version: "3.8"

services:
  server:
    container_name: server
    build: 
      dockerfile: server.Dockerfile
      context: server/
    ports:
      - "8000:8000"
    # volumes:
    #   - ./server:/app
    environment:
      - NODE_ENV=development 
    depends_on: 
      - postgresdb

  client:
    container_name: client
    build: 
      dockerfile: client.Dockerfile
      context: client/
    ports:
      - "80:3000"
    depends_on:
      - server

  postgresdb: 
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

volumes:
  postgres_data:
