version: "3.8"

services:
  server:
    container_name: server
    build: 
      dockerfile: server.Dockerfile
      context: server/
    ports:
      - "8000:8000"
    # volumes:
    #   - ./server:/app
    environment: 
        DATABASE_URL: postgres://postgres:postgres@postgresdb:5432/demo2
    depends_on: 
      - postgresdb

  client:
    container_name: client
    build: 
      dockerfile: client.Dockerfile
      context: client/
    ports:
      - "80:3000"
    depends_on:
      - server

  postgresdb: 
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo2
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
